package Multi_TenantSaaS.SW452.Project;

import Multi_TenantSaaS.SW452.Project.domain.Project;
import Multi_TenantSaaS.SW452.Project.multitenancy.TenantContext;
import Multi_TenantSaaS.SW452.Project.repository.ProjectRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertFalse;

@SpringBootTest
@ActiveProfiles("test")
class ProjectTenantIsolationIntegrationTest {

    @Autowired
    private ProjectRepository projectRepository;

    @Autowired
    private PlatformTransactionManager transactionManager;

    @PersistenceContext
    private EntityManager entityManager;

    private TransactionTemplate tx;

    @BeforeEach
    void setUp() {
        tx = new TransactionTemplate(transactionManager);

        createTenantSchemaAndTables("tenant_1");
        createTenantSchemaAndTables("tenant_2");

        runInTenant("tenant_1", () -> {
            projectRepository.deleteAll();
            entityManager.flush();
            entityManager.clear();
            return null;
        });

        runInTenant("tenant_2", () -> {
            projectRepository.deleteAll();
            entityManager.flush();
            entityManager.clear();
            return null;
        });
    }

    @Test
    void crossTenantRead_shouldNotFindProjectFromAnotherTenant() {
        createTenantSchemaAndTables("tenant_1");
        createTenantSchemaAndTables("tenant_2");

        tx.executeWithoutResult(status -> {
            entityManager.createNativeQuery("""
            INSERT INTO tenant_2.projects (name, description, version)
            VALUES ('Tenant B Project', 'Should not be visible to tenant A', 0)
        """).executeUpdate();
        });

        Long count = tx.execute(status ->
                ((Number) entityManager.createNativeQuery("""
                SELECT COUNT(*) FROM tenant_1.projects
                WHERE name = 'Tenant B Project'
            """).getSingleResult()).longValue()
        );

        assertFalse(count != null && count > 0);
    }

    private void createTenantSchemaAndTables(String schemaName) {
        tx.executeWithoutResult(status -> {
            entityManager.createNativeQuery("CREATE SCHEMA IF NOT EXISTS " + schemaName).executeUpdate();

            entityManager.createNativeQuery("""
                    CREATE TABLE IF NOT EXISTS %s.projects (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        description VARCHAR(255),
                        name VARCHAR(255),
                        version BIGINT
                    )
                    """.formatted(schemaName)).executeUpdate();

            entityManager.createNativeQuery("""
                    CREATE TABLE IF NOT EXISTS %s.tasks (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(255),
                        title VARCHAR(255),
                        version BIGINT,
                        project_id BIGINT
                    )
                    """.formatted(schemaName)).executeUpdate();
        });
    }

    @Test
    void crossTenantList_shouldNotLeakProjectsFromOtherTenant() {
        createTenantSchemaAndTables("tenant_1");
        createTenantSchemaAndTables("tenant_2");

        tx.executeWithoutResult(status -> {
            entityManager.createNativeQuery("""
            INSERT INTO tenant_2.projects (name, description, version)
            VALUES ('Tenant B Hidden Project', 'Should not appear in tenant A list', 0)
        """).executeUpdate();

            entityManager.createNativeQuery("""
            INSERT INTO tenant_1.projects (name, description, version)
            VALUES ('Tenant A Visible Project', 'Should appear only in tenant A list', 0)
        """).executeUpdate();
        });

        Long leakedCount = tx.execute(status ->
                ((Number) entityManager.createNativeQuery("""
                SELECT COUNT(*) FROM tenant_1.projects
                WHERE name = 'Tenant B Hidden Project'
            """).getSingleResult()).longValue()
        );

        Long tenantACount = tx.execute(status ->
                ((Number) entityManager.createNativeQuery("""
                SELECT COUNT(*) FROM tenant_1.projects
                WHERE name = 'Tenant A Visible Project'
            """).getSingleResult()).longValue()
        );

        assertFalse(leakedCount != null && leakedCount > 0);
        assertFalse(tenantACount == null || tenantACount == 0);
    }

    private <T> T runInTenant(String tenantId, TenantOperation<T> operation) {
        TenantContext.setTenantId(tenantId);
        try {
            return tx.execute(status -> operation.execute());
        } finally {
            TenantContext.clear();
        }
    }

    @FunctionalInterface
    private interface TenantOperation<T> {
        T execute();
    }
}